# Generated by Django 6.0.1 on 2026-01-23 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='blogs/')),
                ('itinerario', models.TextField(blank=True, help_text='Ej: Día 1: Lácar. Día 2: Chapelco.')),
                ('servicios', models.CharField(blank=True, help_text='Ej: Hotel, Comida, Guía', max_length=200)),
                ('duracion', models.CharField(blank=True, help_text='Ej: 5 días / 4 noches', max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
