# Generated by Django 6.0.1 on 2026-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='itinerario',
        ),
        migrations.AddField(
            model_name='blog',
            name='dificultad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('N/A', 'No aplica')], default='Baja', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='mejor_epoca',
            field=models.CharField(blank=True, help_text='Ej: Verano, Todo el año, Invierno', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Ej: Permiso de Parques, calzado técnico, entrada paga'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tips',
            field=models.TextField(blank=True, help_text='Consejos personales del autor'),
        ),
        migrations.AddField(
            model_name='blog',
            name='transporte',
            field=models.CharField(blank=True, help_text='Ej: Auto, Barco, 4x4', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 2 horas, Medio día', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='servicios',
            field=models.CharField(blank=True, help_text='Ej: Baños, WiFi, Parador', max_length=200),
        ),
    ]
